project_id = "wempjpyfltayhjzlfwii"

[functions.generate-coupon-message]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.extract-receipt-value]
verify_jwt = false

[functions.create-employee]
verify_jwt = true

[functions.send-notification]
verify_jwt = false
